moneyInput = input("ป้อนจำนวนเงิน: ")
amountOfPeople = input("ป้อนจำนวนคน: ")
productValue = int(moneyInput)/float(amountOfPeople)
productValueText = format(productValue, ".2f")
print("หลังจากหารแล้วจะได้คนละ", productValueText, "บาท")
print("หลังจากหารแล้วจะได้คนละ " + productValueText + " บาท")
print("หลังจากหารแล้วจะได้คนละ {} บาท".format(productValueText))
print(f"หลังจากหารแล้วจะได้คนละ {productValueText} บาท")
